uses:
  - django

python-targets:
  - 3

ignore-patterns:
  - ^peering_manager/configuration.*$

pep8:
  disable:
    - E501

pylint:
  disable:
    - line-too-long
    - bare-except
    - not-callable
