language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - cp peering_manager/configuration.example.py peering_manager/configuration.py
script:
  - ./scripts/cibuild.sh
