language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  allow_failures:
    - python: "3.7"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle coveralls
  - cp peering_manager/configuration.example.py peering_manager/configuration.py
script:
  - ./scripts/cibuild.sh
after_success:
  - coveralls
