language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: "xenial"
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install pycodestyle coveralls
  - cp peering_manager/configuration.example.py peering_manager/configuration.py
script:
  - ./scripts/cibuild.sh
after_success:
  - coveralls
