language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.6"
      env: TOXENV=black
    - python: "3.7"
      dist: "xenial"
      sudo: true
install:
  - pip install tox tox-travis
script:
  - tox
after_success:
  - coveralls
